spring:
  application:
    name: cal
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/llf
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 30
client:
  config:
    my-app-name: cal-config